### ISSUE TITLE
Service Worker + Push Notifications

### ISSUE THREAD

**Issue by JudahGabriel** [pwa-builder/pwabuilder-serviceworkers#43]
Chrome on Android supports web push notifications. I built my PWA to work with push notifications, and it works great on the web. But if I package it with PWABuilder as an Android app, will push notifications still work there? 

I tried this, and sadly it doesn't appear to work. Is there a technical reason?

**Comment by jgw96** [comment]
Hey Judah! So the reason web push notifications dont work in the APK is because the current way we build the android package we use (just rendering your site in a webview basically) does not support web push notifications (standard APKs simply dont allow web push, you must do it on the native side of things). We are evaluating a new android platform that should fix this issue, but i dont have a timeline on that and its still pretty early. Ill leave this issue open for now as it is something we are interested in.

**Comment by everflux** [comment]
So Web Push is not supported for iOS as well?

**Comment by neavilag** [comment]
Hi.  this still an issue. I understand  now the apk is done via TWA. My pwa works fine via web and receives notification. 

 when I run my APK it says it's running on Chrome. But notification are not delivered to the signed apk. 

How can this be accomplished?

**Comment by JudahGabriel** [comment]
@neavilag You should receive push notifications on your device. However, tapping notifications will open in Chrome, rather than your app.

To change this behavior, you can [setup AppLinks](https://stackoverflow.com/a/55449735/536) to open certain domains in your TWA app.) We may update PWABuilder to do this automatically in the future.

I'm closing this issue because the original issue has been fixed by our new TWA generation.

**Comment by daghanacay** [comment]
@JudahGabriel I still do not know how we get the web push notifications on my TWA app created by https://www.pwabuilder.com/ page. 

Actually when I run the APK on my mobile it does not even register a notification token on my back end. Can you please explain how the APK is registered for firebase push notification and receive **web push** notifications through firebase? 

PS: PWA app is correctly registering itself to firebase and receive notifications from firebase.

thanks for your help in advance.

**Comment by eduardohr-muniz** [comment]
Hi, Could you give me instructions on how to get push notifications on Android, please?
